title: >-
  Ideological Polarization in Urban Social Networks:
  A Study of Facebook Event Attendance in Copenhagen (2013–2017)
author: Christian Cole Turner
logo: ""

execute:
  execute_notebooks: "off"

repository:
  url: https://github.com/christian-c-turner/Ideological-Polarization-in-Copenhagen-Facebook-Event-Networks
  branch: main
  path_to_book: ""

html:
  use_issues_button: false
  use_repository_button: true
